development:
  adapter: mysql2
  database: grow_development
  user: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: grow_test
  user: root
  password:
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: grow_production
  user: root
  password:
  pool: 5
  timeout: 5000
